CREATE TABLE `newsbd`.`news` (
  `NEWS_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `NEWS_TITLE` VARCHAR(200) NOT NULL,
  `NEWS_DATE` DATE NOT NULL,
  `NEWS_BRIEF` VARCHAR(400) NULL,
  `NEWS_CONTENT` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`NEWS_ID`),
  UNIQUE INDEX `NEWS_ID_UNIQUE` (`NEWS_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
